// Generated by ui/tools/admin-build.ts. Edit ui/src/features/admin/entry.ts.
// ui/src/generated/diagnostic-policy.ts
var diagnosticPolicy = {
  "version": 1,
  "secretTag": "[secret redacted]",
  "contentTag": "[user content redacted]",
  "publicFields": [
    "actualModel",
    "actual_model",
    "allowance_basis",
    "appVersion",
    "architecture",
    "attemptId",
    "build",
    "category",
    "code",
    "componentStack",
    "content_type",
    "cost_basis",
    "detail",
    "detected_language",
    "domainReason",
    "error",
    "event",
    "exception_type",
    "expected",
    "filename",
    "finishReason",
    "finishReasonOrigin",
    "finish_reason",
    "format",
    "function",
    "id",
    "language_code",
    "level",
    "message",
    "model",
    "model_id",
    "name",
    "nativeVersion",
    "native_finish_reason",
    "openai_processing_ms",
    "operationId",
    "operationKind",
    "param",
    "path",
    "platform",
    "processing_ms",
    "protocol",
    "provider",
    "providerId",
    "provider_name",
    "ratelimit_",
    "read_error",
    "reason",
    "redaction",
    "requestId",
    "request_id",
    "requestedModel",
    "requested_model",
    "retryAfter",
    "retryAt",
    "retry_after",
    "retry_at",
    "route",
    "severity",
    "source",
    "sourceExecutionId",
    "sourceFile",
    "source_file",
    "stack",
    "stage",
    "status",
    "synthesisProfile",
    "syscall",
    "type",
    "x_ratelimit_",
    "x_request_id"
  ],
  "secretFields": [
    "authorization",
    "api_key",
    "key",
    "token",
    "password",
    "secret",
    "cookie",
    "access_token",
    "refresh_token"
  ],
  "contentFields": [
    "content",
    "text",
    "transcript",
    "prompt",
    "messages",
    "answers",
    "questions",
    "state",
    "input",
    "output",
    "audio",
    "audio_base64",
    "data",
    "arguments",
    "reasoning",
    "reasoning_details",
    "request",
    "body",
    "file",
    "url",
    "email",
    "user_id",
    "organization_id"
  ],
  "secretFieldFragments": [
    "secret",
    "password",
    "authorization",
    "api_key",
    "apikey",
    "access_token",
    "accesstoken",
    "refresh_token",
    "refreshtoken",
    "cookie"
  ],
  "limits": {
    "depth": 12,
    "nodes": 1024,
    "fields": 64,
    "array": 64,
    "string": 4096
  },
  "rules": [
    {
      "pattern": "-----BEGIN [^-]*PRIVATE KEY-----[\\s\\S]*?(?:-----END [^-]*PRIVATE KEY-----|$)",
      "flags": "",
      "kind": "secret"
    },
    {
      "pattern": `(\\b(?:authorization|api[_ -]?key|access[_ -]?token|refresh[_ -]?token|password|secret|token|cookie)["']?\\s*[=:]\\s*(?:(?:Bearer|Basic)\\s+)?)(?:"[^"]*"|'[^']*'|[^\\s,;\\[]+)`,
      "flags": "i",
      "kind": "secret",
      "prefix": true
    },
    {
      "pattern": "\\bBearer\\s+[^\\s,;<>]+",
      "flags": "i",
      "kind": "secret"
    },
    {
      "pattern": "\\b(?:sk-|gsk_)[A-Za-z0-9_-]+",
      "flags": "",
      "kind": "secret"
    },
    {
      "pattern": "\\beyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+",
      "flags": "",
      "kind": "secret"
    },
    {
      "pattern": `(?:https?://|content://|blob:|file:///)[^\\s<>"')]+`,
      "flags": "",
      "kind": "secret",
      "terminal": false
    },
    {
      "pattern": "[\\w.+-]+@[\\w.-]+\\.[A-Za-z]{2,}",
      "flags": "",
      "kind": "content"
    },
    {
      "pattern": `(\\b(?:prompt|transcript|content|request body|response body|input|output)["']?\\s*[=:]\\s*)(?:"[^"]*"|'[^']*'|[^;\\n\\[]+)`,
      "flags": "i",
      "kind": "content",
      "prefix": true
    },
    {
      "pattern": "\\b[A-Za-z0-9_-]{48,}\\b",
      "flags": "",
      "kind": "secret",
      "terminal": false
    }
  ]
};

// ui/src/platform/diagnostics/error-details.ts
var isSecret = (key) => diagnosticPolicy.secretFields.includes(key.toLowerCase()) || diagnosticPolicy.secretFieldFragments.some((part) => key.toLowerCase().includes(part));
var sensitive = { test: (key) => isSecret(key) || diagnosticPolicy.contentFields.includes(key.toLowerCase()) };
var publicField = { test: (key) => diagnosticPolicy.publicFields.some((field2) => field2.toLowerCase() === key.toLowerCase()) };
var rules = diagnosticPolicy.rules.map((rule) => ({ ...rule, regex: new RegExp(rule.pattern, `${rule.flags}g`) }));
function scrubErrorText(value, privateValues = []) {
  let text2 = value;
  for (const rule of rules.filter((rule2) => rule2.kind === "secret")) text2 = text2.replace(rule.regex, ("prefix" in rule && rule.prefix ? "$1" : "") + diagnosticPolicy.secretTag);
  for (const content of [...privateValues].filter(Boolean).sort((a, b) => b.length - a.length)) text2 = text2.split(content).join(diagnosticPolicy.contentTag);
  for (const rule of rules.filter((rule2) => rule2.kind !== "secret")) text2 = text2.replace(rule.regex, ("prefix" in rule && rule.prefix ? "$1" : "") + diagnosticPolicy.contentTag);
  text2 = text2.replace(/\(reading (["'])([A-Za-z_$][\w$]*)\1\)/g, "(reading property $2)").replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, "");
  return text2.length > diagnosticPolicy.limits.string ? `${text2.slice(0, diagnosticPolicy.limits.string)}[truncated: string limit]` : text2;
}
function keys(value) {
  try {
    return Object.keys(value);
  } catch {
    return [];
  }
}
function field(value, key) {
  if (typeof value !== "object" || value === null) return void 0;
  try {
    return Reflect.get(value, key);
  } catch {
    return "[unreadable: property]";
  }
}
function errorStack(value, privateValues = []) {
  if (typeof value !== "string") return void 0;
  const lines = value.split("\n").filter((line) => /^\s*at\s|@.*:\d+/.test(line)).slice(0, 32);
  return lines.map((line) => scrubErrorText(line.replace(/(?:https?:\/\/|file:\/\/\/|\/)[^\s()]+/g, (location2) => {
    const clean = location2.replace(/[?#].*?(?=:\d+(?::\d+)?$|$)/, "");
    const source = /(?:^|\/)((?:src|assets)\/[^?#]*:\d+(?::\d+)?)$/.exec(clean);
    return source?.[1] ?? /[^/]+:\d+(?::\d+)?$/.exec(clean)?.[0] ?? "[redacted: location]";
  }), privateValues)).join("\n") || void 0;
}
function errorDetails(error, extra = void 0) {
  const privateValues = [];
  const seen = /* @__PURE__ */ new WeakSet();
  let collectionBudget = 256;
  function collect(value, depth = 0) {
    if (!value || typeof value !== "object" || seen.has(value) || depth > diagnosticPolicy.limits.depth || collectionBudget-- <= 0) return;
    seen.add(value);
    for (const key of keys(value).slice(0, 64)) {
      const item = field(value, key);
      if (sensitive.test(key) && typeof item === "string") privateValues.push(item);
      else collect(item, depth + 1);
    }
  }
  collect(error);
  collect(extra);
  const visited = /* @__PURE__ */ new WeakSet();
  let budget = diagnosticPolicy.limits.nodes;
  function metadata2(value, key = "", depth = 0) {
    if (depth > diagnosticPolicy.limits.depth || budget-- <= 0) return "[truncated: metadata limit]";
    if (typeof value === "string") return publicField.test(key) ? scrubErrorText(value, privateValues) : diagnosticPolicy.contentTag;
    if (value == null || typeof value === "number" || typeof value === "boolean") return value;
    if (typeof value !== "object") return "[omitted: unsupported value]";
    if (visited.has(value)) return "[omitted: circular reference]";
    visited.add(value);
    if (Array.isArray(value)) {
      const items = value.slice(0, diagnosticPolicy.limits.array).map((item) => metadata2(item, key, depth + 1));
      if (value.length > diagnosticPolicy.limits.array) items.push({ truncated_items: value.length - diagnosticPolicy.limits.array });
      return items;
    }
    const names = keys(value).sort((a, b) => Number(!["error", "message", "code", "reason", "stage", "diagnostics", "cause"].includes(a)) - Number(!["error", "message", "code", "reason", "stage", "diagnostics", "cause"].includes(b)));
    const result = Object.fromEntries(names.slice(0, diagnosticPolicy.limits.fields).map((name, index) => {
      if (!/^[\w.-]{1,64}$/.test(name) || privateValues.includes(name)) return [`redacted_field_${index}`, diagnosticPolicy.contentTag];
      return [name, sensitive.test(name) ? isSecret(name) ? diagnosticPolicy.secretTag : diagnosticPolicy.contentTag : metadata2(field(value, name), name, depth + 1)];
    }));
    if (names.length > diagnosticPolicy.limits.fields) result.truncated_fields = names.length - diagnosticPolicy.limits.fields;
    return result;
  }
  const causes = /* @__PURE__ */ new WeakSet();
  function describe(value, depth = 0) {
    if (depth > 4) return { message: "[truncated: cause limit]" };
    if (value && typeof value === "object") {
      if (causes.has(value)) return { message: "[omitted: circular cause]" };
      causes.add(value);
    }
    const message = typeof value === "string" ? value : field(value, "message") ?? field(value, "detail") ?? field(value, "error");
    const cause = field(value, "cause");
    return {
      name: typeof field(value, "name") === "string" ? scrubErrorText(String(field(value, "name")), privateValues) : void 0,
      message: typeof message === "string" && message.trim() ? scrubErrorText(message, privateValues) : "The error did not include an explanation. Inspect the recorded details.",
      code: field(value, "code") == null ? void 0 : metadata2(field(value, "code"), "code"),
      stack: errorStack(field(value, "stack"), privateValues),
      ...cause !== void 0 ? { cause: describe(cause, depth + 1) } : {}
    };
  }
  const envelope = metadata2(typeof error === "string" ? { message: error } : error);
  const diagnosticMetadata = field(envelope, "diagnostics");
  return { ...describe(error), metadata: diagnosticMetadata, fields: envelope, ...extra !== void 0 ? { context: metadata2(extra) } : {}, redaction: "sensitive spans and unclassified fields removed" };
}

// ui/src/features/admin/report-table.ts
var element = (tag, text2) => {
  const node = document.createElement(tag);
  if (text2 !== void 0) node.textContent = text2;
  return node;
};
var number = (value) => typeof value === "number" && Number.isFinite(value) ? value : null;
var count = (value) => number(value)?.toLocaleString("en-US") ?? "\u2014";
var timestamp = (value) => {
  if (typeof value !== "string") return null;
  const time = Date.parse(value);
  return Number.isFinite(time) ? time : null;
};
var dateTime = (value) => {
  const time = timestamp(value);
  return time === null ? "\u2014" : new Date(time).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    timeZone: "UTC"
  });
};
var duration = (value) => {
  const ms = number(value);
  if (ms === null || ms < 0) return "\u2014";
  if (ms < 1e3) return `${ms.toLocaleString("en-US")} ms`;
  if (ms < 6e4) return `${(ms / 1e3).toFixed(2)} s`;
  return `${Math.floor(ms / 6e4)}m ${(ms % 6e4 / 1e3).toFixed(1)}s`;
};
function metadata(value) {
  const details = element("details");
  details.className = "metadata-details";
  details.append(element("summary", "Inspect"), element("pre", JSON.stringify(value, null, 2)));
  return details;
}
function badge(value, tone = "") {
  const node = element("span", value == null ? "\u2014" : String(value));
  node.className = `report-badge ${tone}`;
  return node;
}
var ReportTable = class {
  constructor(columns, options) {
    this.columns = columns;
    this.sortKey = options.sort;
    this.descending = options.descending ?? false;
    this.visible = new Set(columns.filter((c) => !c.hidden || c.required).map((c) => c.key));
    this.node.className = "report-table";
    this.body.className = "scroll report-scroll";
    const tools = element("div");
    tools.className = "table-tools";
    if (options.search) {
      const label = element("label", options.search.label), input = element("input");
      input.type = "search";
      input.placeholder = options.search.label;
      input.oninput = () => {
        this.query = input.value;
        this.render();
      };
      label.append(input);
      tools.append(label);
    }
    const choices = element("details");
    choices.className = "column-choices";
    choices.append(element("summary", "Columns"));
    const list = element("div");
    list.className = "column-list";
    columns.forEach((column) => {
      const label = element("label"), input = element("input");
      input.type = "checkbox";
      input.checked = this.visible.has(column.key);
      input.disabled = !!column.required;
      input.onchange = () => {
        if (input.checked) this.visible.add(column.key);
        else this.visible.delete(column.key);
        if (!this.visible.size) {
          this.visible.add(column.key);
          input.checked = true;
        }
        this.render();
      };
      label.append(input, document.createTextNode(column.label));
      list.append(label);
    });
    choices.append(list);
    tools.append(this.summary, choices);
    const scope = element("p", options.scope);
    scope.className = "table-scope";
    this.body.setAttribute("aria-label", options.label);
    this.node.append(tools, scope, this.body);
    this.label = options.label;
    this.search = options.search;
  }
  rows = [];
  sortKey;
  descending;
  visible;
  query = "";
  body = element("div");
  summary = element("span");
  node = element("div");
  label;
  search;
  update(rows) {
    this.rows = rows;
    this.render();
  }
  render() {
    const query = this.query.toLocaleLowerCase();
    const selected = this.search && query ? this.rows.filter((row) => this.search.text(row).toLocaleLowerCase().includes(query)) : [...this.rows];
    const sorter = this.columns.find((c) => c.key === this.sortKey);
    if (sorter?.value) selected.sort((a, b) => {
      const left = sorter.value(a), right = sorter.value(b);
      if (left == null) return right == null ? 0 : 1;
      if (right == null) return -1;
      const order = typeof left === "number" && typeof right === "number" ? left - right : String(left).localeCompare(String(right));
      return this.descending ? -order : order;
    });
    const columns = this.columns.filter((c) => this.visible.has(c.key)), table2 = element("table");
    table2.setAttribute("aria-label", this.label);
    const head = element("thead"), heading = element("tr"), body = element("tbody");
    columns.forEach((column) => {
      const th = element("th");
      th.scope = "col";
      if (column.numeric) th.className = "numeric";
      if (column.value) {
        const active = column.key === this.sortKey;
        th.setAttribute("aria-sort", active ? this.descending ? "descending" : "ascending" : "none");
        const control = element("button", `${column.label} ${active ? this.descending ? "\u2193" : "\u2191" : "\u2195"}`);
        control.type = "button";
        control.className = "sort-button";
        control.dataset.sortKey = column.key;
        control.setAttribute("aria-label", `Sort by ${column.label}${active ? this.descending ? ", ascending" : ", descending" : ""}`);
        control.onclick = () => {
          this.descending = active ? !this.descending : !!column.numeric;
          this.sortKey = column.key;
          this.render();
          this.body.querySelector(`[data-sort-key="${column.key}"]`)?.focus();
        };
        th.append(control);
      } else th.textContent = column.label;
      heading.append(th);
    });
    head.append(heading);
    selected.forEach((row) => {
      const tr = element("tr");
      columns.forEach((column) => {
        const td = element("td"), value = column.render(row);
        if (column.numeric) td.className = "numeric";
        if (value instanceof HTMLElement) td.append(value);
        else td.textContent = value == null ? "\u2014" : String(value);
        tr.append(td);
      });
      body.append(tr);
    });
    if (!selected.length) {
      const tr = element("tr"), td = element("td", query ? "No loaded records match this search." : "No records loaded in this window.");
      td.colSpan = columns.length;
      td.className = "empty-table";
      tr.append(td);
      body.append(tr);
    }
    table2.append(head, body);
    this.body.replaceChildren(table2);
    this.summary.textContent = `${count(selected.length)} of ${count(this.rows.length)} loaded records`;
    this.summary.setAttribute("role", "status");
  }
};

// ui/src/features/admin/entry.ts
var $ = (id) => document.getElementById(id);
var el = (tag, text2) => {
  const node = document.createElement(tag);
  if (text2 !== void 0) node.textContent = text2;
  return node;
};
var money = (value) => `$${(value / 1e6).toFixed(6)}`;
var text = (value) => value === null || value === void 0 ? "\u2014" : typeof value === "object" ? JSON.stringify(value) : String(value);
var overview;
var cursor = "";
var command;
var logRows = [];
var nextLogPage;
var activeLogQuery = "";
var logSince = "";
var busy = false;
var limitsEnforced = true;
var policyLabels = {
  max_users: "Maximum registered accounts",
  free_daily_micros: "Default daily allowance (USD)",
  extended_daily_micros: "Extended allowance preset (USD)",
  global_daily_micros: "Shared daily allowance (USD)",
  account_requests: "Inference requests / account / day",
  global_requests: "Inference requests / service / day",
  diagnostics_requests: "Account checks / account / day",
  global_diagnostics: "Account checks / service / day"
};
function maskedAccountId(id) {
  const separator = id.indexOf(":");
  const prefix = separator < 0 ? "" : id.slice(0, separator + 1);
  const subject = id.slice(separator + 1);
  return prefix + (subject.length > 9 ? `${subject.slice(0, 3)}\u2026${subject.slice(-6)}` : "\u2022\u2022\u2022");
}
function accountIdentity(user, field2 = "email") {
  const masked = field2 === "email" ? user.email_label ?? "Email unavailable" : maskedAccountId(user.id);
  const node = el("div");
  node.className = "account-identity";
  const hint = el("small", `Click to reveal ${field2}`);
  const control = button(masked, () => {
    if (control.dataset.revealed) {
      control.textContent = masked;
      delete control.dataset.revealed;
      hint.textContent = `Click to reveal ${field2}`;
      control.setAttribute("aria-expanded", "false");
      void renderLive();
      return;
    }
    void run(async () => {
      if (field2 === "email") {
        const result = await api(`/admin/api/users/${encodeURIComponent(user.id)}?days=1`);
        control.textContent = result.identity.email ?? "Email unavailable";
      } else control.textContent = user.id;
      hint.textContent = `Click to hide ${field2}`;
      control.dataset.revealed = "true";
      control.setAttribute("aria-expanded", "true");
    });
  });
  control.className = "identity-toggle";
  control.setAttribute("aria-expanded", "false");
  control.title = `Click to reveal ${field2}; click again to hide`;
  node.append(control, hint);
  return node;
}
var accountTable = new ReportTable([
  { key: "identity", label: "Account", required: true, value: (u) => u.email_label ?? u.id, render: (u) => accountIdentity(u) },
  { key: "id", label: "User ID", value: (u) => u.id, render: (u) => accountIdentity(u, "user ID") },
  { key: "inference", label: "Last inference request (UTC)", value: (u) => timestamp(u.last_inference_at), render: (u) => dateTime(u.last_inference_at) },
  { key: "seen", label: "Last sign-in (UTC)", value: (u) => timestamp(u.last_seen), render: (u) => dateTime(u.last_seen) },
  { key: "used", label: "Allowance used today (USD)", numeric: true, value: (u) => u.usage.micros, render: (u) => money(u.usage.micros) },
  { key: "history", label: "Allowance used \xB7 90 days (USD)", numeric: true, value: (u) => u.usage_90_days_micros, render: (u) => money(u.usage_90_days_micros) },
  { key: "requests", label: "Inference admissions today", numeric: true, value: (u) => number(u.admission.requests), render: (u) => count(u.admission.requests) },
  { key: "limit", label: "Daily allowance (USD)", numeric: true, value: (u) => limitsEnforced ? u.effective_limit_micros : null, render: (u) => limitsEnforced ? money(u.effective_limit_micros) : "Disabled" },
  { key: "source", label: "Limit source", value: (u) => u.daily_limit_micros == null ? "Default" : "Custom", render: (u) => badge(u.daily_limit_micros == null ? "Default" : "Custom") },
  { key: "checks", label: "Account checks today", numeric: true, hidden: true, value: (u) => number(u.admission.diagnostics_requests), render: (u) => count(u.admission.diagnostics_requests) },
  { key: "check-credit", label: "Restored account checks", numeric: true, hidden: true, value: (u) => number(u.admission.diagnostics_requests_credit), render: (u) => count(u.admission.diagnostics_requests_credit) },
  { key: "request-credit", label: "Restored inference requests", numeric: true, hidden: true, value: (u) => number(u.admission.requests_credit), render: (u) => count(u.admission.requests_credit) },
  { key: "allowance-credit", label: "Restored allowance (USD)", numeric: true, hidden: true, value: (u) => u.usage.micros_credit, render: (u) => money(u.usage.micros_credit) },
  { key: "tokens", label: "Tokens today", numeric: true, hidden: true, value: (u) => u.usage.tokens, render: (u) => count(u.usage.tokens) },
  { key: "created", label: "Registered (UTC)", hidden: true, value: (u) => timestamp(u.created_at), render: (u) => dateTime(u.created_at) },
  { key: "version", label: "Session version", numeric: true, hidden: true, value: (u) => u.token_version, render: (u) => count(u.token_version) },
  { key: "inspect", label: "Details", required: true, render: (u) => button("Inspect account", () => void run(() => inspectUser(u))) }
], {
  label: "Accounts",
  scope: "Sorting and search apply to this loaded page (up to 25 accounts). Dates are UTC. Admissions include restored credit; usage includes holds and estimates.",
  sort: "inference",
  descending: true,
  search: { label: "Search masked email or account ID", text: (u) => `${u.email_label ?? ""} ${u.id}` }
});
$("users").replaceChildren(accountTable.node);
var eventTable = new ReportTable([
  { key: "time", label: "Time (UTC)", required: true, value: (r) => timestamp(r.timestamp), render: (r) => dateTime(r.timestamp) },
  { key: "event", label: "Event", required: true, value: (r) => text(r.event), render: (r) => badge(text(r.event).replaceAll("_", " "), String(r.event).endsWith("failed") || r.event === "provider_error_response" ? "report-danger" : "") },
  { key: "duration", label: "Duration", numeric: true, value: (r) => number(r.duration_ms), render: (r) => duration(r.duration_ms) },
  { key: "route", label: "Route", value: (r) => typeof r.route === "string" ? r.route : null, render: (r) => r.route },
  { key: "status", label: "HTTP status", numeric: true, value: (r) => number(r.status), render: (r) => badge(r.status, Number(r.status) >= 400 ? "report-danger" : "") },
  { key: "provider", label: "Provider", hidden: true, value: (r) => typeof r.provider === "string" ? r.provider : null, render: (r) => r.provider },
  { key: "method", label: "Method", hidden: true, value: (r) => typeof r.method === "string" ? r.method : null, render: (r) => r.method },
  { key: "code", label: "Error code", value: (r) => typeof r.code === "string" ? r.code : null, render: (r) => r.code },
  { key: "bytes", label: "Bytes", numeric: true, hidden: true, value: (r) => number(r.bytes), render: (r) => count(r.bytes) },
  { key: "chunks", label: "Chunks", numeric: true, hidden: true, value: (r) => number(r.chunks), render: (r) => count(r.chunks) },
  { key: "tokens", label: "Tokens", numeric: true, hidden: true, value: (r) => number(r.tokens), render: (r) => count(r.tokens) },
  { key: "request", label: "Request ID", hidden: true, value: (r) => typeof r.request_id === "string" ? r.request_id : null, render: (r) => r.request_id },
  { key: "metadata", label: "Metadata", required: true, render: metadata }
], {
  label: "Request events",
  scope: "Sorts loaded events only. Duration measures the named phase: HTTP headers, full request, provider, reservation or settlement. Missing duration is unknown. Search filters this table; the arrival chart uses all loaded events.",
  sort: "time",
  descending: true,
  search: { label: "Search event, route, code or request ID", text: (r) => ["event", "route", "code", "request_id", "provider"].map((k) => text(r[k])).join(" ") }
});
$("logs").replaceChildren(eventTable.node);
var timelineTable = new ReportTable([
  { key: "time", label: "Interval start (UTC)", required: true, value: (p) => timestamp(p.time), render: (p) => dateTime(p.time) },
  { key: "record", label: "Record", value: (p) => p.present ? "Present" : "Missing", render: (p) => p.present ? "Present" : "No record" },
  { key: "usage", label: "Allowance used (USD)", numeric: true, value: (p) => p.present ? p.micros : null, render: (p) => p.present ? money(p.micros) : "\u2014" },
  { key: "tokens", label: "Tokens", numeric: true, value: (p) => p.present ? p.tokens : null, render: (p) => p.present ? count(p.tokens) : "\u2014" },
  { key: "requests", label: "Requests", numeric: true, value: (p) => p.present ? p.requests : null, render: (p) => p.present ? count(p.requests) : "\u2014" }
], { label: "Allowance intervals", scope: "Sorts intervals in the selected chart window. Missing records are unknown.", sort: "time", descending: true });
$("usage-table").replaceChildren(timelineTable.node);
var auditTable = new ReportTable([
  { key: "time", label: "Time (UTC)", required: true, value: (r) => timestamp(r.created_at), render: (r) => dateTime(r.created_at) },
  { key: "action", label: "Action", value: (r) => text(r.action), render: (r) => text(r.action).replaceAll("_", " ") },
  { key: "target", label: "Target", value: (r) => text(r.target), render: (r) => r.target },
  { key: "before", label: "Before", render: (r) => metadata(r.before) },
  { key: "after", label: "After", render: (r) => metadata(r.after) },
  { key: "actor", label: "Administrator", hidden: true, value: (r) => text(r.actor), render: (r) => r.actor }
], { label: "Administrative changes", scope: "Sorts the latest 100 loaded changes.", sort: "time", descending: true });
$("audit-table").replaceChildren(auditTable.node);
async function api(path, body) {
  const response = await fetch(path, {
    credentials: "same-origin",
    cache: "no-store",
    ...body === void 0 ? {} : { method: "POST", headers: { "Content-Type": "application/json", "X-Admin-Action": "1" }, body: JSON.stringify(body) }
  });
  if (!response.ok) {
    const failure = await response.json().catch(() => ({ detail: `HTTP ${response.status}` }));
    throw new Error(`${failure.detail ?? "Request failed"}
HTTP ${response.status}${failure.request_id ? ` \xB7 Request ${failure.request_id}` : ""}${failure.diagnostics ? `
${JSON.stringify(failure.diagnostics, null, 2)}` : ""}${response.status === 401 ? "\nSign in again at /admin/login." : ""}`);
  }
  return response.status === 204 ? void 0 : await response.json();
}
async function run(work) {
  if (busy) return false;
  busy = true;
  $("error").hidden = true;
  $("change-error").hidden = true;
  document.body.setAttribute("aria-busy", "true");
  document.querySelectorAll("button").forEach((button2) => button2.disabled = true);
  try {
    await work();
    return true;
  } catch (error) {
    const notice = $("confirm").open ? $("change-error") : $("error");
    notice.textContent = error instanceof Error ? error.message : String(error);
    notice.hidden = false;
    notice.scrollIntoView({ block: "nearest" });
    return false;
  } finally {
    busy = false;
    document.body.removeAttribute("aria-busy");
    document.querySelectorAll("button").forEach((button2) => button2.disabled = false);
    $("next-users").disabled = !overview?.next_cursor;
    void renderLive();
  }
}
function table(headers, rows) {
  const node = el("table"), head = el("thead"), heading = el("tr"), body = el("tbody");
  headers.forEach((value) => heading.append(el("th", value)));
  head.append(heading);
  rows.forEach((values) => {
    const row = el("tr");
    values.forEach((value) => {
      const cell = el("td");
      if (value instanceof HTMLElement) cell.append(value);
      else cell.textContent = text(value);
      row.append(cell);
    });
    body.append(row);
  });
  node.append(head, body);
  if (!rows.length) {
    const row = el("tr"), cell = el("td", "No records in this window.");
    cell.colSpan = headers.length;
    row.append(cell);
    body.append(row);
  }
  return node;
}
function button(label, action) {
  const node = el("button", label);
  node.type = "button";
  node.onclick = action;
  return node;
}
function usageView(target, rows) {
  renderChart(target, rows.map((row) => ({ ...row, time: `${row.day}T00:00:00Z` })));
}
function renderChart(target, points) {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", "0 0 1000 260");
  svg.setAttribute("role", "img");
  svg.setAttribute("aria-label", "Allowance used per UTC interval in US dollars");
  svg.classList.add("usage-line");
  const draw = (tag, attrs, text2) => {
    const node = document.createElementNS(svg.namespaceURI, tag);
    Object.entries(attrs).forEach(([key, value]) => node.setAttribute(key, value));
    if (text2) node.textContent = text2;
    svg.append(node);
    return node;
  };
  const max = Math.max(1, ...points.map((p) => p.micros)), x = (i) => 100 + i / Math.max(1, points.length - 1) * 870;
  for (let i = 0; i <= 4; i++) {
    const y = 20 + i * 45;
    draw("line", { x1: "100", y1: String(y), x2: "970", y2: String(y), class: "chart-grid" });
    draw("text", { x: "90", y: String(y + 4), "text-anchor": "end" }, money(max * (1 - i / 4)));
  }
  let path = "", connected = false;
  points.forEach((p, i) => {
    if (!p.present) {
      connected = false;
      return;
    }
    const y = 200 - p.micros / max * 180;
    path += `${connected ? "L" : "M"}${x(i)},${y} `;
    connected = true;
    const dot = draw("circle", { cx: String(x(i)), cy: String(y), r: "4", class: "chart-point", tabindex: "0" });
    const title = document.createElementNS(svg.namespaceURI, "title");
    title.textContent = `${p.time} \xB7 ${money(p.micros)} \xB7 ${p.requests} requests \xB7 ${p.tokens} tokens`;
    dot.append(title);
  });
  draw("path", { d: path, class: "chart-line" });
  const ticks = [...new Set(Array.from({ length: Math.min(5, points.length) }, (_, i) => Math.round(i * (points.length - 1) / Math.max(1, Math.min(5, points.length) - 1))))];
  ticks.forEach((i) => {
    const date = new Date(points[i].time);
    draw("text", { x: String(x(i)), y: "228", "text-anchor": i === 0 ? "start" : i === points.length - 1 ? "end" : "middle" }, date.toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" }));
    draw("text", { x: String(x(i)), y: "248", "text-anchor": i === 0 ? "start" : i === points.length - 1 ? "end" : "middle" }, date.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "UTC" }) + " UTC");
  });
  target.replaceChildren(svg);
  if (!points.some((p) => p.present)) target.append(el("p", "No recorded usage in this window. Try a wider range or daily intervals for older records."));
}
async function loadTimeline(pushed) {
  const span = $("chart-range").value, interval = $("chart-interval").value;
  const data = pushed ?? await api(`/admin/api/timeline?span=${span}&interval=${interval}`);
  renderChart($("usage-chart"), data.points);
  $("chart-scope").textContent = data.scope;
  timelineTable.update(data.points);
}
function moneyInput(input) {
  input.type = "text";
  input.inputMode = "decimal";
  input.required = true;
  const group = el("span");
  group.className = "money-input";
  const adjust = (delta) => {
    const amount = parseNumber(input, true);
    input.value = String(Math.max(0, amount + delta * 1e6) / 1e6);
  };
  group.append(
    button("\u2212 $1", () => {
      try {
        adjust(-1);
      } catch (e) {
        $("error").textContent = String(e);
        $("error").hidden = false;
      }
    }),
    input,
    button("+ $1", () => {
      try {
        adjust(1);
      } catch (e) {
        $("error").textContent = String(e);
        $("error").hidden = false;
      }
    })
  );
  return group;
}
function usageTable(rows) {
  const report = new ReportTable([
    { key: "day", label: "UTC day", required: true, value: (r) => r.day, render: (r) => r.day },
    { key: "record", label: "Record", value: (r) => r.present ? "Present" : "Missing", render: (r) => r.present ? "Present" : "Missing" },
    { key: "usage", label: "Used (USD)", numeric: true, value: (r) => r.present ? r.micros : null, render: (r) => r.present ? money(r.micros) : "\u2014" },
    { key: "tokens", label: "Tokens", numeric: true, value: (r) => r.present ? r.tokens : null, render: (r) => r.present ? count(r.tokens) : "\u2014" },
    { key: "requests", label: "Requests", numeric: true, value: (r) => r.present ? r.requests : null, render: (r) => r.present ? count(r.requests) : "\u2014" },
    { key: "credit", label: "Restored allowance (USD)", numeric: true, value: (r) => r.present ? r.micros_credit : null, render: (r) => r.present ? money(r.micros_credit) : "\u2014" }
  ], { label: "Account daily usage", scope: "Sorts the selected account history. Missing records are unknown.", sort: "day", descending: true });
  report.update(rows);
  return report.node;
}
function review(action, target, revision, values, before, effect) {
  command = { operation_id: crypto.randomUUID(), expected_revision: revision, action, target, values };
  const labels = { user_limit: "Change daily allowance", reset_diagnostics: "Restore account checks", reset_requests: "Restore inference requests", reset_allowance: "Restore spending allowance", revoke_sessions: "Revoke sessions", policy: "Change service limits" };
  const display = (key, value) => value === null || value === void 0 ? "Use service default" : key.endsWith("_micros") ? money(Number(value)) : String(value);
  const previous = before && typeof before === "object" ? before : {};
  const changes = Object.entries(values).map(([key, value]) => `${policyLabels[key] ?? (key === "daily_limit_micros" ? "Daily allowance" : key)}: ${display(key, previous[key])} \u2192 ${display(key, value)}`);
  $("change-preview").textContent = `${labels[action] ?? action}
${target}${changes.length ? "\n\n" + changes.join("\n") : ""}`;
  $("change-effect").textContent = effect;
  $("confirm").showModal();
}
function parseNumber(input, dollars) {
  if (!input.value.trim() || !input.checkValidity()) throw new Error(`Invalid value: ${input.labels?.[0]?.textContent ?? input.id}`);
  if (dollars && !/^\d+(?:\.\d{1,6})?$/.test(input.value.trim())) throw new Error("Enter a USD amount such as 5 or 0.50, with at most six decimal places.");
  if (input.max && Number(input.value) > Number(input.max)) throw new Error(`Maximum allowed value is ${dollars ? "$" : ""}${input.max}.`);
  const scaled = Number(input.value) * (dollars ? 1e6 : 1);
  const number2 = Math.round(scaled);
  if (!Number.isSafeInteger(number2) || number2 < 0 || Math.abs(number2 - scaled) > 1e-6) throw new Error("Use a nonnegative whole number or at most six decimal places for USD.");
  return number2;
}
async function loadOverview(live = false, pushed, pushedTimeline) {
  const days = $("days").value;
  const data = pushed ?? await api(`/admin/api/overview?days=${days}&after=${encodeURIComponent(cursor)}`);
  if (!live) overview = data;
  const today = data.global_usage.at(-1);
  $("environment").textContent = data.environment;
  $("administrator").textContent = data.administrator;
  const limited = data.usage_limits_enforced !== false;
  limitsEnforced = limited;
  $("status").textContent = `Snapshot ${new Date(data.generated_at).toLocaleString()} \xB7 ${limited ? "UTC daily limits reset at 00:00." : "Daily usage limits disabled; usage is still recorded."}`;
  $("revision").textContent = `Revision: ${data.revision}`;
  $("summary").replaceChildren(...[
    ["Registered accounts", `${data.account_count} / ${data.policy.max_users}`],
    ["Spending", data.spending_paused ? "Paused" : "Admission enabled"],
    ["Allowance used today", money(today.micros)],
    ["Shared daily limit", limited ? money(data.policy.global_daily_micros) : "Disabled"],
    ["Inference admissions", limited ? `${data.global_admission.account_requests} / ${data.policy.global_requests}` : String(data.global_admission.account_requests)],
    ["Account checks", limited ? `${data.global_admission.diagnostics_requests} / ${data.policy.global_diagnostics}` : String(data.global_admission.diagnostics_requests)]
  ].map(([label, value]) => {
    const card = el("div");
    card.append(el("span", label), el("strong", value));
    return card;
  }));
  await loadTimeline(pushedTimeline);
  if (!live || !document.querySelector("#users [data-revealed]")) accountTable.update(data.users);
  $("next-users").disabled = !data.next_cursor;
  if (live) return;
  $("user-detail").hidden = true;
  const fields = $("policy-fields");
  fields.replaceChildren();
  if (!limited) fields.append(el("p", "Daily limits below apply only when the local server starts with --enforce-usage-limits."));
  for (const [key, label] of Object.entries(policyLabels)) {
    const wrapper = el("label", label), input = el("input"), hint = el("small");
    input.id = `policy-${key}`;
    wrapper.htmlFor = input.id;
    input.type = "number";
    input.min = "0";
    input.required = true;
    const dollars = key.endsWith("_micros");
    input.step = "1";
    input.value = String(data.policy[key] / (dollars ? 1e6 : 1));
    if (dollars) input.max = key === "global_daily_micros" ? "10000" : "1000";
    hint.textContent = `Environment default: ${dollars ? money(data.environment_defaults[key]) : data.environment_defaults[key]}${key === "extended_daily_micros" ? " \xB7 Applied explicitly to individual accounts; existing exceptions keep their values." : ""}`;
    wrapper.append(dollars ? moneyInput(input) : input, hint);
    fields.append(wrapper);
  }
}
async function inspectUser(user) {
  const label = user.email_label ?? "Account details";
  const result = await api(`/admin/api/users/${encodeURIComponent(user.id)}?days=${$("days").value}`);
  user = result.user;
  const pane = $("user-detail");
  pane.hidden = false;
  pane.replaceChildren(el("h3", label), button("Close account details", () => {
    pane.hidden = true;
    pane.replaceChildren();
  }));
  const identity = el("details");
  identity.append(el("summary", "Identity details"), table(["User ID", "Email", "Name"], [[user.id, result.identity.email, result.identity.name]]));
  pane.append(identity);
  const chart = el("div");
  usageView(chart, result.usage);
  pane.append(chart);
  const history = el("details");
  history.append(el("summary", "Daily numeric table"), usageTable(result.usage));
  pane.append(history);
  const controls = el("div");
  controls.className = "filters";
  const limitLabel = el("label", "Custom daily allowance (USD)"), input = el("input");
  input.type = "number";
  input.min = "0";
  input.id = "custom-daily-allowance";
  limitLabel.htmlFor = input.id;
  input.step = "any";
  input.max = "1000";
  input.value = String(user.effective_limit_micros / 1e6);
  limitLabel.append(moneyInput(input));
  controls.append(limitLabel);
  const limitChange = (limit) => review("user_limit", user.id, user.admin_revision, { daily_limit_micros: limit }, { daily_limit_micros: user.daily_limit_micros }, "Applies to subsequent requests. Shared spending and request limits still apply.");
  controls.append(
    button("Set custom limit", () => {
      try {
        limitChange(parseNumber(input, true));
      } catch (error) {
        $("error").textContent = String(error);
        $("error").hidden = false;
      }
    }),
    button("Use default", () => limitChange(null)),
    button("Use extended preset", () => limitChange(overview.policy.extended_daily_micros))
  );
  pane.append(controls);
  const resets = el("div");
  resets.className = "filters";
  for (const [action, label2, effect] of [
    ["reset_diagnostics", "Restore account checks", "Restores today\u2019s personal account-check allowance. Shared request counts remain unchanged."],
    ["reset_requests", "Restore inference requests", "Restores today\u2019s personal inference-request allowance. Shared request counts remain unchanged."],
    ["reset_allowance", "Restore spending allowance", "Grants allowance equal to currently recorded usage, including pending holds. Usage, shared totals, reservations and later settlements remain intact. This can permit additional spending today."],
    ["revoke_sessions", "Revoke sessions", "Invalidates existing app and admin sessions for this account. The user can sign in again; this does not ban the account."]
  ]) resets.append(button(label2, () => review(action, user.id, user.admin_revision, {}, { token_version: user.token_version, today: result.usage.at(-1) }, effect)));
  const reservations = new ReportTable([
    { key: "created", label: "Created (UTC)", required: true, value: (r) => timestamp(r.created_at), render: (r) => dateTime(r.created_at) },
    { key: "state", label: "State", value: (r) => text(r.status), render: (r) => badge(r.status) },
    { key: "elapsed", label: "Created \u2192 updated", numeric: true, value: (r) => reservationDuration(r), render: (r) => duration(reservationDuration(r)) },
    { key: "reserved", label: "Reserved (USD)", numeric: true, value: (r) => number(r.reserved_micros), render: (r) => money(Number(r.reserved_micros)) },
    { key: "recorded", label: "Recorded (USD)", numeric: true, value: (r) => number(r.actual_micros), render: (r) => r.actual_micros == null ? "Unknown" : money(Number(r.actual_micros)) },
    { key: "basis", label: "Cost basis", value: (r) => typeof r.cost_basis === "string" ? r.cost_basis : null, render: (r) => r.cost_basis ?? "Pending / unknown" },
    { key: "tokens", label: "Tokens", hidden: true, numeric: true, value: (r) => number(r.tokens), render: (r) => count(r.tokens) },
    { key: "provider", label: "Provider receipt", hidden: true, value: (r) => typeof r.provider_id === "string" ? r.provider_id : null, render: (r) => r.provider_id },
    { key: "metadata", label: "Metadata", required: true, render: metadata }
  ], { label: "Account reservations", scope: "Latest 100 reservations. Created \u2192 updated is recorded bookkeeping time, not provider execution duration. Unknown cost is not zero.", sort: "created", descending: true });
  reservations.update(result.reservations);
  pane.append(
    resets,
    el("h4", `Registered installations${result.devices_truncated ? " \xB7 limited to 100" : ""}`),
    table(["Platform", "App version", "First seen (UTC)", "Last seen (UTC)"], result.devices.map((row) => [row.platform, row.app_version, dateTime(row.first_seen), dateTime(row.last_seen)])),
    el("h4", `Latest reservations${result.reservations_truncated ? " \xB7 limited to 100" : ""}`),
    reservations.node
  );
  pane.scrollIntoView({ block: "start", behavior: "smooth" });
}
function reservationDuration(row) {
  const start = timestamp(row.created_at), end = timestamp(row.updated_at);
  return start == null || end == null || end < start ? null : end - start;
}
function renderLogs() {
  eventTable.update(logRows);
  const counts = /* @__PURE__ */ new Map(), unique = /* @__PURE__ */ new Set();
  for (const row of logRows) if (row.event === "request_started" && typeof row.timestamp === "string" && typeof row.request_id === "string" && !unique.has(row.request_id)) {
    const date = new Date(row.timestamp);
    if (!Number.isFinite(date.getTime())) continue;
    unique.add(row.request_id);
    const key = date.toISOString().slice(0, 13);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  const days = [...new Set([...counts.keys()].map((key) => key.slice(0, 10)))].sort(), max = Math.max(1, ...counts.values());
  const heatmap = table(["UTC day", ...Array.from({ length: 24 }, (_, hour) => String(hour).padStart(2, "0"))], days.map((day) => [day, ...Array.from({ length: 24 }, (_, hour) => {
    const count2 = counts.get(`${day}T${String(hour).padStart(2, "0")}`) ?? 0, cell = el("span", String(count2));
    cell.className = `heat heat-${Math.ceil(count2 / max * 4)}`;
    cell.title = `${day} ${hour}:00 UTC: ${count2} arrivals in loaded events`;
    return cell;
  })]));
  $("heatmap").replaceChildren(heatmap);
}
async function loadLogs(more = false) {
  if (!more) {
    const params = new URLSearchParams({ hours: $("hours").value, errors: String($("errors-only").checked), request_id: $("request-id").value.trim() });
    activeLogQuery = params.toString();
  }
  const data = await api(`/admin/api/logs?${activeLogQuery}${more && nextLogPage ? `&page_token=${encodeURIComponent(nextLogPage)}&since=${encodeURIComponent(logSince)}` : ""}`);
  logRows = more ? [...logRows, ...data.entries] : data.entries;
  nextLogPage = data.next_page_token;
  logSince = data.since;
  $("log-scope").textContent = `${data.scope} Loaded ${logRows.length} events. ${nextLogPage ? "More events are available; the heat map is incomplete." : "No further pages reported."}`;
  $("more-logs").hidden = !nextLogPage;
  renderLogs();
}
var liveSocket;
var latestLive;
function stopLive(message = "Live is off.") {
  const socket = liveSocket;
  liveSocket = void 0;
  latestLive = void 0;
  socket?.close();
  $("live").checked = false;
  $("live-status").textContent = message;
}
function liveSelection() {
  return {
    days: Number($("days").value),
    after: cursor,
    span: $("chart-range").value,
    interval: $("chart-interval").value,
    hours: Number($("hours").value),
    errors: $("errors-only").checked,
    request_id: $("request-id").value.trim()
  };
}
function subscribeLive() {
  if (liveSocket?.readyState !== WebSocket.OPEN) return;
  liveSocket.send(JSON.stringify(liveSelection()));
}
async function renderLive() {
  if (!latestLive || busy || document.hidden || !liveSocket) return;
  const packet = latestLive;
  if (JSON.stringify(packet.selection) !== JSON.stringify(liveSelection())) return;
  await loadOverview(true, packet.overview, packet.timeline);
  if (!document.querySelector("#logs .metadata-details[open]")) {
    const data = packet.logs;
    logRows = data.entries;
    nextLogPage = void 0;
    logSince = data.since;
    $("log-scope").textContent = data.scope;
    $("more-logs").hidden = true;
    renderLogs();
  }
  $("live-status").textContent = `Live \xB7 connected \xB7 updated ${(/* @__PURE__ */ new Date()).toLocaleTimeString()}.`;
}
function liveFailure(stage, error) {
  const details = errorDetails(error);
  $("error").textContent = `${stage}
${JSON.stringify(details, null, 2)}`;
  $("error").hidden = false;
  stopLive(stage);
}
function startLive() {
  liveSocket?.close();
  latestLive = void 0;
  const url = new URL("/admin/live", location.href);
  url.protocol = location.protocol === "https:" ? "wss:" : "ws:";
  const socket = new WebSocket(url);
  liveSocket = socket;
  $("live-status").textContent = "Live: connecting\u2026";
  socket.onopen = () => {
    if (liveSocket === socket) {
      $("live-status").textContent = "Live \xB7 connected";
      subscribeLive();
    }
  };
  socket.onmessage = (event) => {
    if (liveSocket !== socket) return;
    try {
      const packet = JSON.parse(event.data);
      if (packet.type === "heartbeat") return;
      if (packet.type === "error") {
        $("error").textContent = `${packet.detail}${packet.diagnostics ? "\n" + JSON.stringify(packet.diagnostics, null, 2) : ""}`;
        $("error").hidden = false;
        stopLive(`Live stopped: ${packet.detail}`);
        return;
      }
      if (packet.type !== "snapshot" || !packet.overview || !packet.timeline || !packet.logs) throw new Error("Invalid live update");
      latestLive = packet;
      void renderLive().catch((error) => liveFailure("Live update rendering failed", error));
    } catch (error) {
      liveFailure("Live message decoding failed", error);
    }
  };
  socket.onclose = () => {
    if (liveSocket === socket) stopLive("Live disconnected. Enable Live to reconnect.");
  };
  socket.onerror = () => {
    if (liveSocket === socket) stopLive("Live connection failed. Check the server and your admin session, then enable Live again.");
  };
}
$("live").onchange = () => {
  if ($("live").checked) startLive();
  else stopLive();
};
document.addEventListener("visibilitychange", () => {
  void renderLive().catch((error) => liveFailure("Live update rendering failed", error));
});
$("logs").addEventListener("toggle", () => {
  void renderLive();
}, true);
window.addEventListener("pagehide", () => stopLive());
$("refresh").onclick = () => void run(loadOverview);
$("days").onchange = () => {
  if (liveSocket) subscribeLive();
  else void run(loadOverview);
};
var durations = { "1m": 60, "5m": 300, "10m": 600, "1h": 3600, "12h": 43200, "1d": 86400, "1w": 604800, "1mo": 2592e3, "3mo": 7776e3 };
function chartSelection(changed) {
  const range = $("chart-range"), interval = $("chart-interval");
  const resolution = durations[interval.value] < 3600 ? 60 : durations[interval.value] < 86400 ? 3600 : 86400;
  if (durations[range.value] / resolution > 1440) {
    if (changed === "interval") range.value = resolution === 60 ? "1d" : "1mo";
    else interval.value = durations[range.value] > 3600 * 1440 ? "1d" : "1h";
  }
  if (durations[interval.value] > durations[range.value]) {
    if (changed === "interval") range.value = interval.value;
    else interval.value = range.value;
  }
  if (liveSocket) subscribeLive();
  else void run(() => loadTimeline());
}
$("chart-range").onchange = () => chartSelection("range");
$("chart-interval").onchange = () => chartSelection("interval");
$("first-users").onclick = () => {
  cursor = "";
  if (liveSocket) subscribeLive();
  else void run(loadOverview);
};
$("next-users").onclick = () => {
  cursor = (liveSocket && latestLive ? latestLive.overview.next_cursor : overview?.next_cursor) ?? "";
  if (liveSocket) subscribeLive();
  else void run(loadOverview);
};
$("load-logs").onclick = () => {
  stopLive("Live is off while loading historical logs.");
  void run(() => loadLogs());
};
for (const id of ["hours", "errors-only", "request-id"]) $(id).onchange = () => {
  if (liveSocket) subscribeLive();
};
$("more-logs").onclick = () => {
  stopLive("Live is off while browsing older log pages.");
  void run(() => loadLogs(true));
};
$("load-audit").onclick = () => void run(async () => {
  auditTable.update(await api("/admin/api/audit"));
});
$("logout").onclick = () => void run(async () => {
  stopLive();
  await api("/admin/logout", {});
  location.assign("/admin");
});
$("policy-form").onsubmit = (event) => {
  event.preventDefault();
  if (!overview) return;
  try {
    const values = {}, before = {};
    for (const key of Object.keys(policyLabels)) {
      const value = parseNumber($(`policy-${key}`), key.endsWith("_micros"));
      if (value !== overview.policy[key]) {
        values[key] = value;
        before[key] = overview.policy[key];
      }
    }
    if (Object.keys(values).length) review("policy", "service", overview.policy.revision, values, before, "Updates effective service limits. Lowering a limit can immediately prevent subsequent requests or new registrations. No existing usage is erased.");
  } catch (error) {
    $("error").textContent = String(error);
    $("error").hidden = false;
  }
};
$("cancel-change").onclick = () => {
  command = void 0;
  $("confirm").close();
};
$("apply-change").onclick = () => void run(async () => {
  if (!command) return;
  await api("/admin/api/change", command);
  command = void 0;
  $("confirm").close();
  await loadOverview();
  $("status").textContent += " Change applied and audit record saved.";
});
void run(loadOverview);
