const SEEDS: &[(&str, &str)] = &[
    ("constructs/form.ar.yaml", include_str!("../../../config/constructs/form.ar.yaml")),
    ("constructs/core.yaml", include_str!("../../../config/constructs/core.yaml")),
    ("constructs/navigation.yaml", include_str!("../../../config/constructs/navigation.yaml")),
    ("languages/families.yaml", include_str!("../../../config/languages/families.yaml")),
    ("languages/languages/ar.yaml", include_str!("../../../config/languages/languages/ar.yaml")),
    ("languages/languages/en.yaml", include_str!("../../../config/languages/languages/en.yaml")),
    ("languages/languages/es.yaml", include_str!("../../../config/languages/languages/es.yaml")),
    ("languages/languages/fr.yaml", include_str!("../../../config/languages/languages/fr.yaml")),
    ("languages/languages/zh.yaml", include_str!("../../../config/languages/languages/zh.yaml")),
    ("languages/orthographies.yaml", include_str!("../../../config/languages/orthographies.yaml")),
    ("languages/romanizations.yaml", include_str!("../../../config/languages/romanizations.yaml")),
    ("languages/scripts.yaml", include_str!("../../../config/languages/scripts.yaml")),
    ("languages/traits.yaml", include_str!("../../../config/languages/traits.yaml")),
    ("languages/universal.yaml", include_str!("../../../config/languages/universal.yaml")),
    ("policy/estimator.yaml", include_str!("../../../config/policy/estimator.yaml")),
    ("policy/feedback.yaml", include_str!("../../../config/policy/feedback.yaml")),
    ("starters/everyday.yaml", include_str!("../../../config/starters/everyday.yaml")),
    ("starters/reasons.yaml", include_str!("../../../config/starters/reasons.yaml")),
    ("references.bib", include_str!("../../../references.bib")),
];
