//! Executable reply/translation component for conversation composition. This is
//! not the complete partner workflow: assessment, assistance and speech compose beside
//! it. Source identities are supplied at admission, never generated by a handler.
mod gloss;
use super::{context, prose};
use crate::ai::{connections::access::ResolvedTarget, graph::*, transport::graph_text};
use crate::language::{
    source_graph::{self, SourceText},
    translation_graph::{self as translation, Languages},
};
use std::{collections::BTreeMap, sync::Arc};

pub fn source_binding_contract() -> Contract {
    Contract::new("conversation.bind-reply-source", 1)
}

fn required(contract: Contract) -> Port {
    Port {
        contract,
        optional: false,
    }
}
fn output(node: &str, port: &str) -> Source {
    Source::Output {
        node: node.into(),
        port: port.into(),
    }
}

/// Register the reusable operations once, including the named type conversion
/// from generated text plus an admitted source ID into a reading source value.
pub fn register(
    registry: &mut Registry,
    reply: prose::Provider,
    translate: translation::Provider,
    word_gloss: crate::language::gloss_graph::Provider,
) -> Result<()> {
    context::register(registry)?;
    prose::register(registry, reply)?;
    source_graph::register(registry)?;
    translation::register(registry, translate)?;
    crate::language::gloss_graph::register(registry, word_gloss)?;
    let identity = Contract::new("reading.source-identity", 1);
    registry.define_type(identity.clone(), Shape::Text)?;
    let binding = source_binding_contract();
    registry.register(
        Operation {
            contract: binding.clone(),
            implementation: "conversations/execution/reply-source/1".into(),
            inputs: BTreeMap::from([
                ("id".into(), required(identity.clone())),
                ("text".into(), required(prose::text_contract())),
            ]),
            outputs: BTreeMap::from([("source".into(), required(translation::source_contract()))]),
            resource: Resource::Local,
            reuse: Reuse::Exact,
        },
        Arc::new(|_, values| {
            Box::pin(async move {
                let id = values["id"]
                    .as_str()
                    .filter(|id| !id.is_empty())
                    .ok_or(Fault {
                        code: "reply_source_invalid".into(),
                        path: "id".into(),
                    })?;
                Ok(BTreeMap::from([(
                    "source".into(),
                    serde_json::json!({
                        "id":id,"text":values["text"],
                    }),
                )]))
            })
        }),
    )
}

/// Build the component using the same operation registry as its enclosing graph.
pub fn definition(kind: context::Kind) -> Definition {
    let identity = Contract::new("reading.source-identity", 1);
    let binding = source_binding_contract();
    let mut inputs = prose::inputs();
    inputs.get_mut("context").unwrap().contract = context::captured_contract();
    inputs.insert("reply_source_id".into(), required(identity));
    inputs.insert(
        "learner_source".into(),
        required(translation::source_contract()),
    );
    inputs.insert(
        "languages".into(),
        required(translation::languages_contract()),
    );
    for (name, port) in graph_text::inputs() {
        inputs.insert(format!("reading_{name}"), port);
    }
    let mut prose_bindings: BTreeMap<_, _> = prose::inputs()
        .keys()
        .map(|name| (name.clone(), Source::Input(name.clone())))
        .collect();
    prose_bindings.insert("context".into(), output("context", "context"));
    let translation_bindings = |source| {
        let mut bindings: BTreeMap<_, _> = graph_text::inputs()
            .keys()
            .map(|name| (name.clone(), Source::Input(format!("reading_{name}"))))
            .collect();
        bindings.insert("languages".into(), Source::Input("languages".into()));
        bindings.insert("source".into(), source);
        bindings
    };
    let mut nodes = BTreeMap::from([
        (
            "context".into(),
            Node {
                operation: context::operation_contract(),
                inputs: BTreeMap::from([("context".into(), Source::Input("context".into()))]),
                after: vec![],
                guard: None,
                activation: Activation::Automatic,
            },
        ),
        (
            "reply".into(),
            Node {
                operation: prose::operation_contract(),
                inputs: prose_bindings,
                after: vec![],
                guard: None,
                activation: Activation::Automatic,
            },
        ),
        (
            "reply_source".into(),
            Node {
                operation: binding,
                inputs: BTreeMap::from([
                    ("id".into(), Source::Input("reply_source_id".into())),
                    ("text".into(), output("reply", "text")),
                ]),
                after: vec![],
                guard: None,
                activation: Activation::Automatic,
            },
        ),
        (
            "learner_translation".into(),
            Node {
                operation: translation::operation_contract(),
                inputs: translation_bindings(Source::Input("learner_source".into())),
                after: vec!["context".into()],
                guard: None,
                activation: Activation::OnDemand,
            },
        ),
        (
            "reply_translation".into(),
            Node {
                operation: translation::operation_contract(),
                inputs: translation_bindings(output("reply_source", "source")),
                after: vec![],
                guard: None,
                activation: Activation::OnDemand,
            },
        ),
    ]);
    let mut outputs = BTreeMap::from([
        ("text".into(), required(prose::text_contract())),
        (
            "reply_source".into(),
            required(translation::source_contract()),
        ),
        (
            "learner_translation".into(),
            Port {
                contract: translation::result_contract(),
                optional: true,
            },
        ),
        (
            "reply_translation".into(),
            Port {
                contract: translation::result_contract(),
                optional: true,
            },
        ),
    ]);
    let mut results = BTreeMap::from([
        ("text".into(), output("reply", "text")),
        ("reply_source".into(), output("reply_source", "source")),
        (
            "learner_translation".into(),
            output("learner_translation", "translation"),
        ),
        (
            "reply_translation".into(),
            output("reply_translation", "translation"),
        ),
    ]);
    // Opening and exchange are distinct graph definitions. No source value is
    // fabricated for an opening and no optional value feeds a required port.
    let name = if matches!(kind, context::Kind::Reply) {
        "conversation.reply-reading"
    } else {
        inputs.remove("learner_source");
        nodes.remove("learner_translation");
        outputs.remove("learner_translation");
        results.remove("learner_translation");
        "conversation.opening-reading"
    };
    let mut definition = Definition {
        contract: Contract::new(name, 1),
        inputs,
        nodes,
        outputs,
        results,
        compositions: BTreeMap::new(),
    };
    gloss::extend(&mut definition, kind);
    definition
}

pub fn compile(
    kind: context::Kind,
    reply: prose::Provider,
    translate: translation::Provider,
    word_gloss: crate::language::gloss_graph::Provider,
) -> Result<Executable> {
    let mut registry = Registry::default();
    register(&mut registry, reply, translate, word_gloss)?;
    registry.compile(definition(kind))
}

pub struct Captured {
    pub context: context::Captured,
    pub learner_source: Option<SourceText>,
    pub reply_source_id: String,
    pub languages: Languages,
    pub gloss_settings: crate::language::linguistics::adapter::settings::Settings,
    pub gloss_target: ResolvedTarget,
    pub reply_target: ResolvedTarget,
    pub reading_target: ResolvedTarget,
    pub install_id: String,
}

pub fn capture(captured: Captured) -> Result<Values> {
    if captured.reply_source_id.is_empty() {
        return Err(Fault {
            code: "reply_source_invalid".into(),
            path: "reply_source_id".into(),
        });
    }
    let source_matches =
        match (&captured.context.kind, &captured.learner_source) {
            (context::Kind::Reply, Some(source)) => {
                !source.id.is_empty()
                    && source.id != captured.reply_source_id
                    && captured.context.messages.last().is_some_and(|message| {
                        message.role == "user" && message.content == source.text
                    })
            }
            (context::Kind::Opening | context::Kind::SeededOpening, None) => true,
            _ => false,
        };
    if !source_matches {
        return Err(Fault {
            code: "reply_source_invalid".into(),
            path: "learner_source".into(),
        });
    }
    let mut values = prose::capture(
        captured.context,
        &captured.reply_target,
        &captured.install_id,
        1.1,
    )?;
    for (name, value) in graph_text::capture(
        &captured.reading_target,
        &captured.install_id,
        crate::ai::connections::model_routing::TASK_TEMPERATURE,
    )? {
        values.insert(format!("reading_{name}"), value);
    }
    gloss::capture(
        &mut values,
        captured.gloss_settings,
        &captured.gloss_target,
        &captured.install_id,
    )?;
    values.insert(
        "reply_source_id".into(),
        serde_json::json!(captured.reply_source_id),
    );
    values.insert("languages".into(), serde_json::json!(captured.languages));
    if let Some(source) = captured.learner_source {
        values.insert("learner_source".into(), serde_json::json!(source));
    }
    Ok(values)
}

#[cfg(test)]
mod tests;
