# Generated by npm run contracts; edit content/shared/speech-routing.yaml.
import json
SOURCE_SHA256 = "11f972700201de9430e259c5655e21c2e9a313574c6237cdc1c02e1255009083"
CATALOG = json.loads("{\"models\":{\"eleven_v3\":{\"provider\":\"elevenlabs\",\"task\":\"speech\"},\"scribe_v2\":{\"provider\":\"elevenlabs\",\"task\":\"transcription\"},\"whisper-large-v3\":{\"provider\":\"groq\",\"task\":\"transcription\"},\"whisper-large-v3-turbo\":{\"provider\":\"groq\",\"task\":\"transcription\"}}}")
