# Generated by npm run contracts; edit content/speech/speech-routing.yaml.
import json
SOURCE_SHA256 = "0bda985f1c82850c5ba43a2f4ed3a203b95982bb8c55c969afb1d19f1163f786"
CATALOG = json.loads("{\"models\":{\"eleven_v3\":{\"provider\":\"elevenlabs\",\"task\":\"speech\"},\"eleven_v4_turbo\":{\"provider\":\"elevenlabs\",\"task\":\"speech\"},\"scribe_v2\":{\"provider\":\"elevenlabs\",\"task\":\"transcription\"},\"whisper-large-v3\":{\"provider\":\"groq\",\"task\":\"transcription\"},\"whisper-large-v3-turbo\":{\"provider\":\"groq\",\"task\":\"transcription\"}}}")
