# Generated by npm run contracts; edit content/speech/speech-routing.yaml.
import json
SOURCE_SHA256 = "ef0d312a2c1caf7cd08a18925323a45b7006bcbee4f3563da70dd722966b5c2f"
CATALOG = json.loads("{\"models\":{\"eleven_v3\":{\"provider\":\"elevenlabs\",\"task\":\"speech\"},\"eleven_v4_turbo\":{\"provider\":\"elevenlabs\",\"task\":\"speech\"},\"scribe_v2\":{\"provider\":\"elevenlabs\",\"task\":\"transcription\"},\"whisper-large-v3\":{\"provider\":\"groq\",\"task\":\"transcription\"},\"whisper-large-v3-turbo\":{\"provider\":\"groq\",\"task\":\"transcription\"}}}")
