// @vitest-environment jsdom
import { useState } from 'react'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, expect, it, vi } from 'vitest'
import type { Persona, PersonaDetails } from '../../contracts'
import { PersonaProfileDialog } from './PersonaProfileDialog'

const persona: Persona = { id: 'persona', learnerId: 'learner', languageId: 'es', revision: 1, details: { name: 'Carmen', romanizedName: null, age: 44, location: 'Sevilla', occupation: 'Teacher', background: '', currentSituation: '', interests: [], opinions: [], interestingFacts: [], favoriteBooks: [], favoriteMovies: [], manner: '', quirks: [], vibe: ['🌿', '🌊'] } }
beforeEach(() => {
  HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', '') }
  HTMLDialogElement.prototype.close = function () { this.removeAttribute('open') }
})
function Fixture({ save }: { save: (persona: Persona, details: PersonaDetails) => Promise<Persona> }) {
  const [saved, setSaved] = useState(persona)
  const [open, setOpen] = useState(true)
  return <><button onClick={() => setOpen(true)}>Open profile</button>{open && <PersonaProfileDialog persona={saved} language="Spanish" romanized={false} onNewPersona={vi.fn()} onSave={async (base, details) => { const next = await save(base, details); setSaved(next); return next }} onClose={() => setOpen(false)} />}</>
}
it('Escape flushes a focused field before closing; reopening reads the saved value', async () => {
  let resolve!: (persona: Persona) => void
  const save = vi.fn().mockImplementation(() => new Promise<Persona>(done => { resolve = done }))
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  const name = screen.getByRole('textbox', { name: 'Name' })
  await user.click(name); await user.clear(name); await user.type(name, 'Revised')
  expect(save).not.toHaveBeenCalled()
  await user.keyboard('{Escape}')
  expect(save).toHaveBeenCalledExactlyOnceWith(persona, { ...persona.details, name: 'Revised' })
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  resolve({ ...persona, revision: 2, details: { ...persona.details, name: 'Revised' } })
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  await user.click(screen.getByRole('button', { name: 'Open profile' }))
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Revised')
})
it('a settled failed save cannot be discarded by closing; successful retry permits reopen', async () => {
  const save = vi.fn().mockRejectedValue(new Error('Save rejected'))
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Draft' } })
  fireEvent.blur(screen.getByRole('textbox', { name: 'Name' }))
  await screen.findByText('Save rejected')
  await user.keyboard('{Escape}')
  await waitFor(() => expect(save).toHaveBeenCalledTimes(2))
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Draft')
  save.mockImplementation(async (base: Persona, details: PersonaDetails) => ({ ...base, revision: 2, details }))
  await user.click(screen.getByRole('button', { name: 'Close Persona' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  await user.click(screen.getByRole('button', { name: 'Open profile' }))
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Draft')
})
it('blank-name validation retains the focused draft on Escape without a command', async () => {
  const save = vi.fn()
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  await user.clear(screen.getByRole('textbox', { name: 'Name' }))
  await user.keyboard('{Escape}')
  expect(await screen.findByText('Name must be nonempty and be at most 80 characters.')).toBeInTheDocument()
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('')
  expect(save).not.toHaveBeenCalled()
})

it('offers a way into a new persona from the editor', async () => {
  const onNewPersona = vi.fn()
  render(<PersonaProfileDialog persona={persona} language="Spanish" romanized={false} onSave={vi.fn()} onNewPersona={onNewPersona} onClose={vi.fn()} />)
  fireEvent.click(screen.getByRole('button', { name: 'New persona…' }))
  await waitFor(() => expect(onNewPersona).toHaveBeenCalledOnce())
})

it('Escape saves a focused list without requiring blur', async () => {
  const save = vi.fn().mockImplementation(async (base: Persona, details: PersonaDetails) => ({ ...base, revision: 2, details }))
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  const interests = screen.getByRole('textbox', { name: 'Interests' })
  await user.click(interests)
  await user.type(interests, 'Cycling{Enter}Markets')
  expect(save).not.toHaveBeenCalled()
  await user.keyboard('{Escape}')
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(save).toHaveBeenCalledExactlyOnceWith(persona, { ...persona.details, interests: ['Cycling', 'Markets'] })
  await user.click(screen.getByRole('button', { name: 'Open profile' }))
  expect(screen.getByRole('textbox', { name: 'Interests' })).toHaveValue('- Cycling\n- Markets')
})

it('invalid focused list survives Escape and can be discarded without saving', async () => {
  const save = vi.fn()
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  const interests = screen.getByRole('textbox', { name: 'Interests' })
  await user.click(interests)
  const invalid = 'x'.repeat(1000)
  fireEvent.change(interests, { target: { value: invalid } })
  await user.keyboard('{Escape}')
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  expect(interests).toHaveValue(invalid)
  expect(save).not.toHaveBeenCalled()
  await user.click(screen.getByRole('button', { name: 'Discard unsaved changes' }))
  expect(screen.getByRole('textbox', { name: 'Interests' })).toHaveValue('')
  await user.keyboard('{Escape}')
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(save).not.toHaveBeenCalled()
})

it('Clear can be discarded and closed without saving', async () => {
  const save = vi.fn()
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  await user.click(screen.getByRole('button', { name: 'Clear' }))
  await user.keyboard('{Escape}')
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Discard unsaved changes' }))
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Carmen')
  await user.click(screen.getByRole('button', { name: 'Close Persona' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(save).not.toHaveBeenCalled()
})

it('explicit discard does not autosave a focused valid list before restoring', async () => {
  const save = vi.fn()
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  await user.click(screen.getByRole('textbox', { name: 'Interests' }))
  await user.type(screen.getByRole('textbox', { name: 'Interests' }), 'Unsaved')
  await user.click(screen.getByRole('button', { name: 'Discard unsaved changes' }))
  expect(screen.getByRole('textbox', { name: 'Interests' })).toHaveValue('')
  expect(save).not.toHaveBeenCalled()
})

it('failed saves remain recoverable by explicit discard without another write', async () => {
  const save = vi.fn().mockRejectedValue(new Error('Conflict'))
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Unsaved' } })
  await user.keyboard('{Escape}')
  await screen.findByText('Conflict')
  await user.click(screen.getByRole('button', { name: 'Discard unsaved changes' }))
  await user.keyboard('{Escape}')
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(save).toHaveBeenCalledTimes(1)
})

it('New persona preserves invalid edits until they are explicitly discarded', async () => {
  const onNewPersona = vi.fn()
  const save = vi.fn()
  render(<PersonaProfileDialog persona={persona} language="Spanish" romanized={false} onSave={save} onNewPersona={onNewPersona} onClose={vi.fn()} />)
  const user = userEvent.setup()
  await user.click(screen.getByRole('button', { name: 'Clear' }))
  await user.click(screen.getByRole('button', { name: 'New persona…' }))
  await screen.findByText('Name must be nonempty and be at most 80 characters.')
  expect(onNewPersona).not.toHaveBeenCalled()
  await user.click(screen.getByRole('button', { name: 'Discard unsaved changes' }))
  await user.click(screen.getByRole('button', { name: 'New persona…' }))
  await waitFor(() => expect(onNewPersona).toHaveBeenCalledOnce())
  expect(save).not.toHaveBeenCalled()
})

it.each(['close button', 'backdrop', 'native cancel', 'new persona'])('%s saves pending list edits through the same exit policy', async (exit) => {
  const save = vi.fn().mockImplementation(async (base: Persona, details: PersonaDetails) => ({ ...base, revision: 2, details }))
  const close = vi.fn()
  const newPersona = vi.fn()
  render(<PersonaProfileDialog persona={persona} language="Spanish" romanized={false} onSave={save} onNewPersona={newPersona} onClose={close} />)
  const user = userEvent.setup()
  const interests = screen.getByRole('textbox', { name: 'Interests' })
  await user.click(interests)
  fireEvent.change(interests, { target: { value: 'Cycling' } })
  if (exit === 'close button') await user.click(screen.getByRole('button', { name: 'Close Persona' }))
  if (exit === 'backdrop') fireEvent.click(screen.getByRole('dialog'), { clientX: -1 })
  if (exit === 'native cancel') fireEvent(screen.getByRole('dialog'), new Event('cancel', { bubbles: false, cancelable: true }))
  if (exit === 'new persona') await user.click(screen.getByRole('button', { name: 'New persona…' }))
  await waitFor(() => expect(exit === 'new persona' ? newPersona : close).toHaveBeenCalledOnce())
  expect(save).toHaveBeenCalledExactlyOnceWith(persona, { ...persona.details, interests: ['Cycling'] })
})

it.each(['Escape', 'native cancel'])('%s saves the focused pending Vibe emoji once', async (exit) => {
  const save = vi.fn().mockImplementation(async (base: Persona, details: PersonaDetails) => ({ ...base, revision: 2, details }))
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  const add = screen.getByRole('textbox', { name: 'Add a Vibe emoji' })
  await user.click(add)
  fireEvent.change(add, { target: { value: '👩🏽‍🍳' } })
  expect(save).not.toHaveBeenCalled()
  if (exit === 'Escape') await user.keyboard('{Escape}')
  else fireEvent(screen.getByRole('dialog'), new Event('cancel', { bubbles: false, cancelable: true }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(save).toHaveBeenCalledExactlyOnceWith(persona, { ...persona.details, vibe: ['🌿', '🌊', '👩🏽‍🍳'] })
  await user.click(screen.getByRole('button', { name: 'Open profile' }))
  expect(screen.getByRole('button', { name: 'Remove 👩🏽‍🍳' })).toBeInTheDocument()
})

it('invalid pending Vibe input blocks closing and can be explicitly discarded', async () => {
  const save = vi.fn()
  render(<Fixture save={save} />)
  const user = userEvent.setup()
  const add = screen.getByRole('textbox', { name: 'Add a Vibe emoji' })
  await user.click(add)
  fireEvent.change(add, { target: { value: 'not an emoji' } })
  await user.keyboard('{Escape}')
  expect(screen.getByRole('dialog')).toBeInTheDocument()
  expect(add).toHaveValue('not an emoji')
  expect(await screen.findByText('Each Vibe entry must be one emoji. not an emoji is not an emoji.')).toBeInTheDocument()
  expect(save).not.toHaveBeenCalled()
  await user.click(screen.getByRole('button', { name: 'Discard unsaved changes' }))
  expect(screen.getByRole('textbox', { name: 'Add a Vibe emoji' })).toHaveValue('')
  await user.keyboard('{Escape}')
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(save).not.toHaveBeenCalled()
})
