use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Closed vocabulary emitted by the graph implementation, not free-form provider prose.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum CoreFaultCode {
    InspectionLimit,
    InspectionRevision,
    RevisionLimit,
    HistoryLimit,
    HistoryRequired,
    HistoryMismatch,
    SnapshotMismatch,
    AdmissionHeld,
    AlreadySettled,
    ArtifactMismatch,
    BindingSet,
    CancelledBeforeDispatch,
    CheckpointArtifactMismatch,
    CheckpointByteLimit,
    CheckpointCorrupt,
    CheckpointEventLimit,
    CheckpointIdentity,
    CheckpointVersion,
    CompositionChanged,
    CompositionDepth,
    DependencyCycle,
    DuplicateArtifact,
    DuplicateComposition,
    DuplicateControl,
    DuplicateNode,
    DuplicateOperation,
    DuplicateRun,
    DuplicateType,
    EffectRequiresOwner,
    GraphLimit,
    IdentityLimit,
    IncompatiblePort,
    InputsUnavailable,
    InterruptedBeforeDispatch,
    InvalidAdoption,
    InvalidCheckpoint,
    InvalidConstant,
    InvalidDemand,
    InvalidDispatch,
    InvalidGuard,
    InvalidIdentifier,
    InvalidRetry,
    InvalidValue,
    InvalidVersion,
    MissingResult,
    MissingWork,
    ReloadRequired,
    Revoked,
    RevokedOrPaused,
    Serialization,
    SettlementLimit,
    UnexpectedPort,
    UnknownArtifact,
    UnknownAttempt,
    UnknownControlParent,
    UnknownExecution,
    UnknownInput,
    UnknownNode,
    UnknownOperation,
    UnknownOutput,
    UnknownPolicyNode,
    UnknownRun,
    UnknownType,
}
