/** Compile the one authored privacy policy for each runtime; --check is the CI gate. */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
const root = new URL('../', import.meta.url)
const source = readFileSync(new URL('redaction-policy/policy.json', root), 'utf8')
const policy = JSON.parse(source)
for (const rule of policy.rules) new RegExp(rule.pattern, rule.flags)
const outputs = new Map([
  ['native/gen/android/app/src/main/assets/diagnostic-policy.json', source],
  ['ui/src/generated/diagnostic-policy.ts', `// Generated by tools/diagnostic-policy.ts; edit redaction-policy/policy.json.\nexport const diagnosticPolicy = ${JSON.stringify(policy, null, 2)} as const\n`],
  ['server/app/diagnostics/policy.py', `# Generated by tools/diagnostic-policy.ts; edit redaction-policy/policy.json.\nimport json\nPOLICY = json.loads(${JSON.stringify(source)})\n`],
])
for (const [name, content] of outputs) {
  const path = fileURLToPath(new URL(name, root))
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`Stale diagnostic policy: ${name}`)
  } else writeFileSync(path, content)
}
