/** Deterministic standalone admin assets; no Node runtime or CDN in the server image. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import ts from 'typescript'
const root = resolve(import.meta.dirname, '../..')
const destination = resolve(root, 'server/app/diagnostics/admin_assets')
const source = readFileSync(resolve(root, 'ui/src/features/admin/entry.ts'), 'utf8')
const output = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText
const assets = { 'admin.js': '// Generated by ui/tools/admin-build.ts. Edit ui/src/features/admin/entry.ts.\n' + output,
  'admin.css': readFileSync(resolve(root, 'ui/src/styles/foundations/tokens.css'), 'utf8') + '\n' + readFileSync(resolve(root, 'ui/src/styles/features/admin.css'), 'utf8'),
  'index.html': readFileSync(resolve(root, 'ui/tools/admin.html'), 'utf8') }
mkdirSync(destination, { recursive: true })
for (const [name, contents] of Object.entries(assets)) {
  const path = resolve(destination, name)
  if (process.argv.includes('--check')) { if (readFileSync(path, 'utf8') !== contents) throw new Error(`Stale admin asset: ${name}`) }
  else writeFileSync(path, contents)
}
