/** Design proposal: session-only fixtures. No persistence, credentials, microphone or AI. */
import { mockIPC } from '@tauri-apps/api/mocks'
import { createRoot } from 'react-dom/client'
import { useEffect, useRef, useState } from 'react'
import { I18nProvider } from '../src/components/localization/i18n'
import { VarietyField } from '../src/features/settings/language/VarietyField'
import { ConversationChoices } from '../src/features/conversation/session/ConversationChoices'
import { ComposerInput } from '../src/features/conversation/composer/ComposerInput'
import { useAppearance } from '../src/platform/appearance/useAppearance'
import type { ConversationStartConfig } from '../src/generated/contracts'
import { PREVIEW_SETTINGS } from './preview-settings'
import '../src/styles/index.css'
import './onboarding-preview.css'

mockIPC(() => { throw new Error('Native actions are unavailable in the onboarding design preview.') })
const varieties = [{ id: 'spanish-spain', label: 'Spain' }, { id: 'spanish-mexico', label: 'Mexico' }]
const topics = [{ id: 'food', label: 'Food' }, { id: 'weekend', label: 'Your weekend' }]
const initial: ConversationStartConfig = { difficulty: 'beginner', varietyId: 'spanish-spain', direction: { topic: null, timeReference: 'any', usePersonaDetails: true } }
const titles = ['Choose your languages', 'Connect AI access', 'Your first conversation', 'Practice with Lucía']
const notes = [
  ['Start with a useful choice, without a welcome carousel.', 'Reuse the language catalog and variety control. This fixture only offers Spanish; the finished screen must use the complete catalog.', 'Save a language shortcut without creating a conversation. Explanation language and interface language are separate.'],
  ['Reuse the existing AI access settings and their validation. The controls here simulate those routes; they are not a replacement settings implementation.', 'Set up later enters the app with a visible connection notice.', 'Connection and voice availability need separate truthful states; a successful text connection does not prove speech works.'],
  ['This is the conversation start surface, outside the setup wizard.', 'Keep the default language partner. Existing partner management remains available in the app; no mandatory profile creation.', 'Difficulty is a preference, not an assessment. Topic and grammar choices are optional.', 'Starting is the explicit AI request boundary in the finished app.'],
  ['One inline hint at a time. No spotlight overlay or forced click sequence.', 'Word help and playback only appear when their resources are ready. This prototype shows a reading-help placeholder, not real audio or gloss interaction.', 'Record simulates permission handling. No microphone is accessed.', 'Coach guidance appears only after a learner sends a message. No evidence or rewards are generated by this fixture.'],
]

function Preview() {
  const [step, setStep] = useState(0)
  const [dark, setDark] = useState(false)
  const [narrow, setNarrow] = useState(false)
  const [config, setConfig] = useState(initial)
  const [explanation, setExplanation] = useState('english')
  const [route, setRoute] = useState('Hosted sign-in')
  const [connected, setConnected] = useState(false)
  const [failure, setFailure] = useState(false)
  const [denyMic, setDenyMic] = useState(false)
  const [notice, setNotice] = useState('')
  const [hint, setHint] = useState(0)
  const [input, setInput] = useState('')
  const [sent, setSent] = useState('')
  const [recording, setRecording] = useState(false)
  const [custom, setCustom] = useState(false)
  const [customText, setCustomText] = useState('')
  const heading = useRef<HTMLHeadingElement>(null)
  useAppearance({ ...PREVIEW_SETTINGS, theme: dark ? 'dark' : 'light' })
  useEffect(() => { heading.current?.focus() }, [step])
  function go(next: number) { setNotice(''); setStep(next) }
  function reset() { go(0); setConnected(false); setSent(''); setInput(''); setHint(0); setRecording(false); setConfig(initial); setCustom(false); setCustomText(''); setExplanation('english') }
  function send(value: string) { setSent(value); setInput(''); setHint(previous => previous < 0 ? previous : 2); setNotice('Sample message only. Nothing was sent to an AI service.') }
  return <I18nProvider locale="english"><main className="onboarding-review" data-narrow={narrow}>
    <header>
      <h1>Onboarding · Interactive design proposal</h1>
      <p>Sample data only. Changes last until this page reloads. No sign-in, saved settings, recording or AI requests.</p>
      <div className="review-actions">
        <button className="btn" onClick={reset}>Restart setup</button>
        <button className="btn" aria-pressed={narrow} onClick={() => setNarrow(!narrow)}>Narrow layout</button>
        <button className="btn" aria-pressed={dark} onClick={() => setDark(!dark)}>Dark theme</button>
        <label className="check-label"><input type="checkbox" checked={failure} onChange={e => setFailure(e.target.checked)} />Connection fails</label>
        <label className="check-label"><input type="checkbox" checked={denyMic} onChange={e => setDenyMic(e.target.checked)} />Microphone denied</label>
      </div>
    </header>
    <div className="review-layout">
      <section className="review-screen" aria-label="Proposed app screen">
        <p className="review-meta">SkellySpeak · {step < 2 ? `Setup ${step + 1} of 2` : 'Conversation'}</p>
        <h2 ref={heading} tabIndex={-1}>{titles[step]}</h2>
        {step === 0 && <>
          <div className="form-row"><label htmlFor="practice-language">I want to practice</label><select id="practice-language" value="spanish" onChange={() => {}}><option value="spanish">Spanish · Español</option></select></div>
          <div className="form-row"><span>Variety</span><VarietyField presets={varieties} value={config.varietyId} onChange={varietyId => setConfig({ ...config, varietyId })} /></div>
          <div className="form-row"><label htmlFor="explanation-language">Explain things in</label><select id="explanation-language" value={explanation} onChange={e => setExplanation(e.target.value)}><option value="english">English</option><option value="spanish">Español</option></select></div>
          <p className="field-note">You can change these choices and add more languages later.</p>
          <details><summary>Interface language</summary><p>English</p><p className="field-note">The app’s buttons and menus can use a different language from your explanations.</p></details>
          <footer className="review-footer"><button className="btn primary" onClick={() => go(1)}>Continue</button></footer>
        </>}
        {step === 1 && <>
          <p>Connect an AI service for conversations and feedback. You can browse the app before connecting.</p>
          <div className="form-row"><label htmlFor="access-route">AI access</label><select id="access-route" value={route} onChange={e => { setRoute(e.target.value); setConnected(false); setNotice('') }}>{['Hosted sign-in', 'API keys', 'Custom URL'].map(label => <option key={label}>{label}</option>)}</select></div>
          <div className="review-note"><p>{route === 'Hosted sign-in' ? 'Sign in with Google using your SkellySpeak account.' : route === 'API keys' ? 'Use the existing OpenRouter and Groq credential controls.' : 'Use the existing server address and connection health controls.'}</p><p className="review-meta">Preview: connection is simulated; do not enter credentials.</p>
            <button className="btn" disabled={connected} onClick={() => { setConnected(!failure); setNotice(failure ? 'Could not connect. Try again or set up later.' : 'Sample connection ready.') }}>{connected ? 'Connected' : 'Simulate connection'}</button>
          </div>
          <footer className="review-footer"><button className="btn" onClick={() => go(0)}>Back</button><button className="btn primary" disabled={!connected} onClick={() => go(2)}>Continue</button><button className="btn" onClick={() => { setConnected(false); go(2) }}>Set up later</button></footer>
        </>}
        {step === 2 && <>
          <p>Spanish · {varieties.find(v => v.id === config.varietyId)?.label} · Explanations in {explanation === 'english' ? 'English' : 'Spanish'}</p>
          <p><strong>Lucía</strong> · Your conversation partner</p>
          {!connected && <div className="review-note"><p>AI access is not connected. You can choose your conversation settings now.</p><button className="btn" onClick={() => go(1)}>Set up AI access</button></div>}
          <ConversationChoices value={config} topics={topics} disabled={false} onChange={setConfig} onCustom={() => setCustom(true)} />
          {custom && <div className="form-row"><label htmlFor="custom-topic">Custom topic</label><input className="field" id="custom-topic" value={customText} onChange={e => setCustomText(e.target.value)} /><button className="btn" disabled={!customText.trim()} onClick={() => { setConfig({ ...config, direction: { ...config.direction, topic: { kind: 'custom', text: customText.trim() } } }); setCustom(false) }}>Use topic</button></div>}
          <p className="field-note">Choose a comfortable difficulty. You can change it during the conversation.</p>
          <footer className="review-footer"><button className="btn" onClick={() => go(0)}>Change languages</button><button className="btn primary" disabled={!connected} onClick={() => go(3)}>Let Lucía start</button></footer>
        </>}
        {step === 3 && <>
          <p className="review-meta">Fixed sample opening; topic and difficulty do not generate different replies in this preview.</p>
          <div className="review-message" lang="es">¡Hola! ¿Qué te gusta hacer los fines de semana?</div>
          {sent && <div className="review-learner" lang="es">{sent}</div>}
          {hint >= 0 && <aside className="review-note" aria-label="Optional help">
            <strong>{['Understanding a reply', 'Making your reply', 'Using the coach'][hint]}</strong>
            <p>{['Use word help to understand unfamiliar words. Playback is available when the message’s audio is ready.', 'Record a reply, or type below. If you need ideas, use reply help beside the composer.', 'After you send a message, open the coach for feedback on that turn. You can keep talking while feedback is prepared.'][hint]}</p>
            <div className="review-actions">{hint === 0 && <button className="btn" onClick={() => setHint(1)}>Next tip</button>}<button className="btn" onClick={() => setHint(-1)}>Dismiss help</button></div>
          </aside>}
          <ComposerInput input={input} available sending={false} recording={recording} transcribing={false} autoSend={false} targetLanguageTag="es" targetLanguageName="Spanish" onInput={setInput} onSend={send} onDiscardRecording={() => setRecording(false)} onToggleRecording={() => {
            if (denyMic) { setRecording(false); setNotice('Microphone access is blocked. You can type, or allow microphone access in device settings and try again.'); return }
            setRecording(!recording)
            if (recording) { setInput('Me gusta caminar.'); setNotice('Sample transcript inserted. Review it before sending.') }
            else setNotice('Simulated recording. Press Stop to insert a sample transcript.')
          }} />
          <footer className="review-footer"><button className="btn" onClick={() => { setHint(0); setNotice('') }}>Show help again</button><button className="btn" onClick={() => go(2)}>Conversation choices</button></footer>
        </>}
        {notice && <p role="status">{notice}</p>}
      </section>
      <aside className="review-aside"><h2>Review notes</h2><ol>{notes[step].map(note => <li key={note}>{note}</li>)}</ol><p>Proposed flow: Languages → AI access → Conversation → Optional hints.</p><p>Review controls above are outside the proposed app UI.</p></aside>
    </div>
  </main></I18nProvider>
}
createRoot(document.getElementById('root')!).render(<Preview />)
