"""Decisions share admission/billing but never the chat endpoint or streaming."""
import json
import pytest
from fastapi import HTTPException
from server.app.inference import decisions, grouped


def fixture(modality="speech_transcript"):
    # Generated by the real native dispatch test, not a parallel Python schema.
    from pathlib import Path
    name = 'jev-native-text-request.json' if modality == 'text' else 'jev-native-request.json'
    return json.loads((Path(__file__).parent / 'fixtures' / name).read_text())



def test_decisions_reserve_repeated_state_and_adapt_usage_without_losing_original():
    request = fixture()
    validated = decisions.request(request)
    assert validated.payload == request
    assert validated.reserve_micros > 0
    assert decisions.endpoint('https://openrouter.ai/api/v1') == 'https://openrouter.ai/api/alpha/decisions'
    raw = {'id': 'fixture', 'model': decisions.MODEL, 'usage': {'cost': .0005, 'input_tokens': 123, 'output_tokens': 45}, 'answers': {'skill': {'choice': 'partial'}}}
    result = decisions.completion(raw)
    assert result['usage']['prompt_tokens'] == 123
    assert result['usage']['completion_tokens'] == 45
    assert result['usage']['cost'] == raw['usage']['cost']
    assert json.loads(result['choices'][0]['message']['content']) == raw['answers']
    assert result['answers'] == raw['answers']


@pytest.mark.parametrize('change', ['model', 'extra', 'coverage', 'nan', 'large', 'context'])
def test_invalid_requests_rejected_before_admission(change):
    body = fixture()
    if change == 'model': body['model'] = 'arbitrary/provider'
    elif change == 'extra': body['provider'] = {'allow_fallbacks': True}
    elif change == 'coverage': body['questions'].pop(next(iter(body['questions'])))
    elif change == 'nan': body['state']['input']['suggestion'] = float('nan')
    elif change == 'large': body['state']['currentLearnerMessage'] = 'x' * 30_000
    else: body['state']['precedingExchange'] = [{'role': [], 'content': 'x'}]
    with pytest.raises(HTTPException) as error:
        decisions.request(body)
    assert error.value.status_code == 400


def test_grouped_decisions_do_not_accept_streaming_deltas():
    body = {'version': 2, 'items': [{'operation_id': 'a' * 32, 'attempt_id': '1234567890-' + 'b' * 32, 'request': fixture()}]}
    parsed = grouped.parse(body, max_tokens=2048)
    assert parsed[0].contract.payload['model'] == decisions.MODEL
    body['items'][0]['deltas'] = True
    with pytest.raises(HTTPException):
        grouped.parse(body, max_tokens=2048)


@pytest.mark.parametrize('modality', ['text', 'speech_transcript'])
def test_native_input_modalities_pass_grouped_admission_unchanged(modality):
    request = fixture(modality)
    assert request['state']['input']['modality'] == modality
    body = {'version': 2, 'items': [{'operation_id': 'a' * 32,
            'attempt_id': '1234567890-' + 'b' * 32, 'request': request}]}
    parsed = grouped.parse(body, max_tokens=2048)
    assert parsed[0].contract.payload == request


@pytest.mark.parametrize('modality', ['speech', 'audio', '', None, []])
def test_unsupported_modalities_are_rejected(modality):
    request = fixture()
    request['state']['input']['modality'] = modality
    with pytest.raises(HTTPException) as error:
        decisions.request(request)
    assert error.value.status_code == 400


@pytest.mark.parametrize('flag_bits', range(8))
@pytest.mark.parametrize('modality', ['text', 'speech_transcript'])
def test_native_contract_with_every_assistance_combination(modality, flag_bits):
    body = fixture(modality)
    flags = body['state']['input']
    flags['modality'] = modality
    for bit, name in enumerate(('suggestion', 'revision', 'scaffold')):
        flags[name] = bool(flag_bits & (1 << bit))
    body['state']['precedingExchange'] = [
        {'role': role, 'content': text} for role, text in
        [('assistant', '¿Adónde?'), ('user', '北京'), ('assistant', 'مرحبا'), ('user', 'Demain.')]]
    assert decisions.request(body).payload == body


def test_context_limit_uses_native_compact_utf8_byte_count():
    body = fixture()
    longest = max(decisions.encoded_size(q) for q in body['questions'].values())
    body['state']['currentLearnerMessage'] = ''
    allowed = 28_000 - 4096 - longest - decisions.encoded_size(body['state'])
    body['state']['currentLearnerMessage'] = 'é' * (allowed // 2) + 'x' * (allowed % 2)
    assert decisions.request(body).payload == body
    body['state']['currentLearnerMessage'] += 'x'
    with pytest.raises(HTTPException):
        decisions.request(body)
